# Generated by Django 2.0.7 on 2018-08-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgpd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicename', models.CharField(max_length=20)),
                ('devicemodel', models.CharField(max_length=10)),
                ('devicedsc', models.CharField(max_length=50)),
                ('devicestatus', models.CharField(max_length=10)),
            ],
        ),
    ]
