# Generated by Django 2.0.7 on 2018-08-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgpd', '0002_devices'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='devices',
            table='devices',
        ),
    ]
