# Generated by Django 2.0.7 on 2018-08-15 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgpd', '0003_auto_20180803_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
